### ISSUE TITLE
Bug in views/date_based.py

### ISSUE THREAD

**Issue by everythingability** [dokterbob/django-agenda#1]
Line 62 ...

problem: objects = objects.filter(slug_contains=slug)
answer: a missing _

**Comment by dokterbob** [comment]
Actually, it was line 58. In the future, please feel free to submit a patch using GIT. It's easier for you as well as for me.

Create a patch as follows: git format-patch HEAD^

Either way, thanks for the feedback!

**Comment by everythingability** [comment]
I have no idea how :-)

I'm working on integrating it with jQuery stuff for nicer presentation. I'll let you know how I get on..

Tom

**Comment by dokterbob** [comment]
http://help.github.com/forking 

Anyways, if you're going to add jQuery functionality, please try to make it optional and keep the jQuery/JavaScript code seperate as much as you can as not every situation lends itself for AJAX. Then again, it looks nice.

Will surely merge if you implement this well. :)
