### ISSUE TITLE
Doesn't work with Python 2.6

### ISSUE THREAD

**Issue by yuriiz** [dokterbob/django-agenda#5]
Attempt to use it with Python 2.6/Django 1.3 fails:

```
TemplateSyntaxError at /admin/agenda/event/1/

Caught ViewDoesNotExist while rendering: Could not import agenda.views.vobject_django. Error was: No module named _thread
```

Have tried in two environments:

```
> python
Python 2.6.7 (r267:88850, Jul 12 2011, 11:28:50) 
[GCC 4.2.1 20070719  [FreeBSD]] on freebsd8
Type "help", "copyright", "credits" or "license" for more information.
>>> import _thread
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _thread
```

```
# python
Python 2.6.5 (r265:79063, Apr 16 2010, 13:57:41) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _thread
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _thread
```

**Comment by dokterbob** [comment]
Hey Yuriiz,

The django-agenda up has not been maintained for a VERY long time.

However, it seems that this problem is related to the vobject module, as 
I'm pretty sure I'm not using threads anywhere in the code. Did you try 
upgrading vobject with `pip install --upgrade vobject`?

Kind regards,
Mathijs de Bruin

Op 12-07-11 09:39, yuriiz schreef:

> Attempt to use it with Python 2.6/Django 1.3 fails:
> 
> ```
> TemplateSyntaxError at /admin/agenda/event/1/
> 
> Caught ViewDoesNotExist while rendering: Could not import agenda.views.vobject_django. Error was: No module named _thread
> ```
> 
> Have tried in two environments:
> 
> ```
> > python
> Python 2.6.7 (r267:88850, Jul 12 2011, 11:28:50)
> [GCC 4.2.1 20070719  [FreeBSD]] on freebsd8
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import _thread
> Traceback (most recent call last):
>    File "<stdin>", line 1, in<module>
> ImportError: No module named _thread
> ```
> 
> ```
> # python
> Python 2.6.5 (r265:79063, Apr 16 2010, 13:57:41)
> [GCC 4.4.3] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import _thread
> Traceback (most recent call last):
>    File "<stdin>", line 1, in<module>
> ImportError: No module named _thread
> ```

**Comment by yuriiz** [comment]
Hi,

I've found a problem. It was not in django-agenda itself but in dateutil.rrule module used by django-agenda. It uses _thread module which is available only in Python 3. Changing it to use thread.Lock() fixed the problem.

Thanks,
Yurii
